# netlify.toml (в корне проекта)

[build]
  command = "npm run build"
  publish = "dist"
  base = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  # !!! ПЕРЕПРОВЕРЬТЕ ЭТОТ URL !!!
  to = "https://ВАШ_RENDER_URL.onrender.com/:splat"
  status = 200
  force = true