[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  base = "client"

[[redirects]]
  from = "/api/*"
  to = "https://yaanime.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200