[build]
  command = "npm run build"
  publish = "dist"
  base = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://yaanime.onrender.com/:splat"
  status = 200
  force = true